apiVersion: v1
kind: Namespace
metadata:
  name: exercises
  labels:
    name: exercises
    purpose: devops-with-kubernetes-exercises

---

apiVersion: v1
kind: Namespace
metadata:
  name: project
  labels:
    name: project
    purpose: devops-with-kubernetes-project