apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: exercises
  name: shared-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
