apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-backend-configmap
  namespace: project
data:
  port: "3001"
  service_name: "todo-backend"
  POSTGRES_DB: ps_db
  POSTGRES_USER: ps_user
  POSTGRES_PASSWORD: SecurePassword
