apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  namespace: project
  labels:
    app: todo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: aljazkovac/todo-backend:latest
          imagePullPolicy: Always
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-backend-configmap
                  key: port
            - name: SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: todo-backend-configmap
                  key: service_name
            - name: INITIAL_TODO_ID
              valueFrom:
                configMapKeyRef:
                  name: todo-backend-configmap
                  key: initial_todo_id
          ports:
            # Documents which port the container listens on (not strictly required but best practice)
            - containerPort: 3001
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
