apiVersion: v1
kind: Service
metadata:
  name: todo-backend-svc
  namespace: project
  labels:
    app: todo-backend
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
  selector:
    app: todo-backend
